### ISSUE TITLE
Url issue

### ISSUE THREAD

**Issue by eeian** [jasonchriscodes/Speed#32]
![issue1](https://user-images.githubusercontent.com/80303355/196873995-e0f6605c-66ac-4f81-91f1-e4a33aac64be.png)

**Comment by SINGHAJS** [comment]
Sorry, don't feel like it.

**Comment by eeian** [comment]
Just fix it lol

**Comment by SINGHAJS** [comment]
Sounds Good! Working on it.

**Comment by eeian** [comment]
Thanks Ajit!
